Add -version flag
grpc-ecosystem/grpc-health-probe pull request #146
Opened 2023-06-13 04:49 UTC by superfrink

Added `-version` flag.  Exits non-zero so accidentally running with this flag will not indicate a service is up. 

Typical output:
```
$ ./grpc-health-probe -version
git b35a00f4192e0a0654c9e1ff6e7400513e2d000a 2023-06-13T04:13:12Z
```

When built when there are local changes not checked into Git:
```
$ ./grpc-health-probe -version
git 1089f40639043ee46cc47cbea1bcb0cc48cfc284 2023-06-12T16:41:19Z (built with changes outside version control)
```

When not built with VCS information:
```
$ go run main.go -version
vcs info was not included in build
exit status 5
```

Note, Go does not include the Git tag in the build information included in the executable.  If we want to do something like that, in the past I have had a build job run a script that runs `git` commands and writes the output into strings in a `.go` file that gets included in the build.

2023-06-13 05:50 UTC, ahmetb commented
I prefer to maintain less code if possible. Can you instead use "go version -m BINARY"?

2023-06-13 06:46 UTC, superfrink commented
Yes, that works if you have go inside the container.  Do you want to close #14?

2023-06-22 03:24 UTC, ahmetb requested changes

2023-06-22 03:24 UTC, ahmetb commented on main.go
> +		log.Println(probeVersion())
I think we should just do `fmt.Println`

2023-06-22 03:24 UTC, ahmetb commented on main.go
> +		os.Exit(StatusNotChecked)
what do you think about exiting successfully with `0`? if someone specifies `-version` I think that's their intent, and they might be writing scripts that ensure some specific version is installed. in that case, non-zero exit codes will be harder to work with.

2023-06-22 03:24 UTC, ahmetb commented on main.go
> +	vcsDetails := map[string]string{"vcs": "", "vcs.revision": "", "vcs.time": "", "vcs.modified": ""}
vcs.revision alone should be ok. we can print it as
`commit 32e62eebfeb40e4deb6faad70ad9b7f328bbe5e9 (dirty)`

2023-06-22 04:25 UTC, superfrink commented on main.go
> +		os.Exit(StatusNotChecked)
Yeah, it's a bit contrived to try to prevent a mistake where someone accidentally puts `-version` in a script where they don't want it.

2023-06-22 04:45 UTC, superfrink commented on main.go
> +	vcsDetails := map[string]string{"vcs": "", "vcs.revision": "", "vcs.time": "", "vcs.modified": ""}
Change made.

Output:
```
$ ./grpc-health-probe -version

commit 6f187c727d89d16799e3c831d9837b8006f00c3f
```

When there are changes not checked in:
```
$ ./grpc-health-probe -version
commit 32e62eebfeb40e4deb6faad70ad9b7f328bbe5e9 (dirty)
```

Output when no vcs build info is included:
```
$ go run main.go -version
vcs info was not included in build
```

2023-06-22 04:46 UTC, superfrink commented on main.go
> +		os.Exit(StatusNotChecked)
Updated.

2023-06-22 05:12 UTC, superfrink commented
I often prefer having a list of keys instead of long `if ... else if ... ` structures.  In this case where all we want is the commit hash and dirty status the code can be simplified by removing the `vcsDetails` map.

2023-06-23 03:05 UTC, superfrink commented
The GoReleaser build for windows arm64 failed.  The error is `cgoAvailable` is redeclared.  `go/src/net/cgo_stub.go` has
```
// cgoAvailable set to false to indicate that the cgo resolver
// is not available on this system.
const cgoAvailable = false
```
and `go/src/net/lookup_windows.go` has:
```
// cgoAvailable set to true to indicate that the cgo resolver
// is available on Windows. Note that on Windows the cgo resolver
// does not actually use cgo.
const cgoAvailable = true
```

On a Linux machine it appears to build manually:
```
$ GOOS=windows GOARCH=arm64 go build
go: downloading github.com/Microsoft/go-winio v0.6.1

$ file grpc-health-probe.exe
grpc-health-probe.exe: PE32+ executable (console) Aarch64 (stripped to external PDB), for MS Windows
```

I wonder if importing `runtime/debug` is causing this.

2023-06-23 03:13 UTC, ahmetb commented
This might be the old version of goreleaser doing something wrong as well.

2023-06-23 04:16 UTC, superfrink commented
The build logs show it's interpreting the go version 1.20 as 1.2.  It seems to be using a release candiate 1.21.0-rc2 instead of 1.2 or 1.20.

```
Run actions/setup-go@v1
with:

...

  go-version: 1.2

...

env:
  GOROOT: /opt/hostedtoolcache/go/1.21.0-rc2/x64
```

I wrapped the 1.20 in single quotes.  That seems to work.

2023-06-23 04:18 UTC, ahmetb commented
Good catch this probably broke during 1.19 → 1.20 and we probably built a few releases with go1.2 by mistake.

2023-06-23 04:22 UTC, superfrink commented
I wonder if this is a new issue in the 1.21 rc?  Just a guess.  When I built it manually on the command line I used 1.20.5.

I just went back through the actions logs to find the latest that succeeded.  It seems to have interpreted 1.20 as 1.20.5.  https://github.com/grpc-ecosystem/grpc-health-probe/actions/runs/5308777585/jobs/9608631371

2023-06-23 15:28 UTC, ahmetb approved these changes

2023-06-27 16:37 UTC, merged