Added support for Spiffe for fetching TLS credentials.
grpc-ecosystem/grpc-health-probe pull request #63
Opened 2021-04-15 22:51 UTC by edwarnicke

2021-04-16 01:22 UTC, ahmetb commented
Thanks for submitting this but I need to understand under what circumstance a health check probe/sidecar needs spiffe credentials. Can you please explain your motive?

2021-04-16 16:04 UTC, edwarnicke commented
@ahmetb Delighted to explain!

I have a GRPC service that is being published in a Pod in K8s.  It gets its credentials using the [Spiffe Workload API](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Workload_API.md).  

I would like to be able to use grpc-health-probe in K8s to provide readiness and liveliness probes (basically, exactly the example you have in your docs, which is super helpful BTW :) ).

The problem being: credentials come from (and get rotated by) the [Spiffe Workload API](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Workload_API.md).  They do not come from files.

It occurred to me as GRPC is very popular, and Spiffe is growing in popularity, a lot of folks would have the same problem, and so I adapted grpc-health-probe to do so.

Does that help answer your question?

2021-04-16 16:46 UTC, ahmetb commented
Got it. I’ll do some more research myself as well.

Do you think there's a "generic way" of getting credentials from SPIFFE that can be passed to this tool? For example, in your code I see a x509 provider.

Could this potentially mean that maybe instead of integrating SPIFFE, the users should have saved a secret onto disk, then use the probe like:

    grpc_health_probe -mtls-key=/path/to/spiffe.key -mtls-cert=/path/to/spiffe.cert

The reason I ask for this is that if we accept SPIFFE today, we need to also accept its alternatives tomorrow to give equal treatment. (For example, Kubernetes does not support gRPC probes natively, because it would also mean it should also accept Apache Thrift or other RPC framework probes.)

So if there's a way to do this in a generic way that would support other identity frameworks or mTLS providers in the future, we should try to go that way maybe?

I’m not against integrating SPIFFE, just trying to see if there's a more modular/reusable way that SPIFFE can benefit from and would prevent us accepting its alternatives into the source code in the future.

2021-04-16 16:55 UTC, edwarnicke commented
@ahmetb Having been on the other end of something with the potential to bloat infinitely with options, I completely get your concern, and complement you on the friendliness of your expression of it :)

Would something like this work:
```
grpc_health_probe -tls-exec grpc_spiffe_provider
```

The idea being that a grpc-*-provider is a simple executable with a simple contract:

```
grpc_*_provider ${tmpdir}
```

that writes the appropriate files with conventional names to the provided ${tmpdir} which grpc_health_probe is responsible for both creating and removing when its done with it.

This way, the next time someone comes through with a request like mine, you can point them to that and they can write something ultra simple.  If you were so inclined, you could even offer to keep an index of such providers in your README.md to ease your users path in finding them :)

Thoughts?

2021-04-19 17:57 UTC, ahmetb commented
Yeah that looks quite nasty. I guess we can go with your proposed implementation.
Can you please explain how does this work with SPIRE as well?

2021-04-20 18:52 UTC, edwarnicke commented
Yes!  It does work with Spire! (in fact, I tested it with Spire)

2021-04-20 19:41 UTC, edwarnicke commented
I've also tested it in K8s with Spire :)

2021-04-22 00:52 UTC, edwarnicke commented
@ahmetb Anything else needed to get the PR into a mergeable form?

2021-04-22 01:21 UTC, ahmetb commented on README.md
> +| **5** | failure: could not retrieve TLS credentials using the Spiffe Workload API |
Can we reserve low numbers to more generic errors that we might add in the future?

Let's give this something above 20 if that is ok (also pls update the code).

2021-04-22 01:22 UTC, ahmetb commented on README.md
> +## Health checking TLS Servers with Spiffe issued credentials
let's use proper spelling SPIFFE and let's link to its homepage somewhere.

2021-04-22 01:24 UTC, ahmetb commented on README.md
> +If a gRPC is serving traffic over TLS, or uses TLS client authentication to authorize clients, and the [Spiffe Workload
I think we can shorten this paragraph as:

> If your gRPC server requires authentication, you can use the following command line options and set the `FOO` environment variable.

2021-04-22 01:24 UTC, ahmetb commented on main.go
> +	flSpiffe        bool
capitalize like GZIP above

2021-04-22 01:25 UTC, ahmetb commented on main.go
> +	flagSet.BoolVar(&flSpiffe, "spiffe", false, "use Spiffe to aquire TLS certificates (default: false)")
ditto use SPIFFE spelling.

typo in acquire.

also are these credentials or certificates?

2021-04-22 01:26 UTC, ahmetb commented on main.go
> +			log.Printf("SVID: %q", svid.ID)
svid is not very descriptive. I don't know what it means, chances are others won't either.

2021-04-22 01:28 UTC, ahmetb commented on main.go
> +	flagSet.BoolVar(&flSpiffe, "spiffe", false, "use Spiffe to aquire TLS certificates (default: false)")
I think we can say:

> use SPIFFE to obtain mTLS credentials

2021-04-22 01:31 UTC, ahmetb commented on main.go
> +	} else if flSpiffe {
so by adding this you now complicated the simple operating modes we had: -tls or lack thereof.

now I can pass this program both -tls and -spiffe. and i have no way of knowing what will get used (without inspecting the source code).

two options: either we make this require -tls, because honestly it uses TLS. or we make -spiffe flag mutually exclusive with -tls and **explicitly** error out when both are specified.

2021-04-22 01:31 UTC, ahmetb requested changes
Initial code review.

2021-04-22 01:43 UTC, edwarnicke commented on README.md
> +| **5** | failure: could not retrieve TLS credentials using the Spiffe Workload API |
Done :)

2021-04-22 01:44 UTC, edwarnicke commented on README.md
> +If a gRPC is serving traffic over TLS, or uses TLS client authentication to authorize clients, and the [Spiffe Workload
Done :)

2021-04-22 01:46 UTC, edwarnicke commented on main.go
> +	flagSet.BoolVar(&flSpiffe, "spiffe", false, "use Spiffe to aquire TLS certificates (default: false)")
Done.  These are TLS certificates.

2021-04-22 01:46 UTC, edwarnicke commented on main.go
> +			log.Printf("SVID: %q", svid.ID)
Fixed :)

2021-04-22 01:47 UTC, edwarnicke commented on main.go
> +	} else if flSpiffe {
Excellent point... went with mutually exclusive, as the interaction of -tls with potentially two sets of other options (the existing -tls options or the -spiffe option) felt overly complex to explain to the user.

2021-04-22 01:47 UTC, edwarnicke commented
> Initial code review.

I *think* I've fixed your initial concerns :)   Many thanks for the detailed code review :)

2021-04-27 22:34 UTC, edwarnicke commented
@ahmetb Any further feedback?

2021-04-27 23:35 UTC, ahmetb approved these changes

2021-04-27 23:35 UTC, ahmetb commented
Thanks for reminding this.

2021-04-27 23:35 UTC, merged

2021-04-28 00:03 UTC, edwarnicke commented
@ahmetb Thank you for merging!
Question: When do you plan to do a new release? :)